name: body_building
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.3.0
  google_fonts: ^3.0.1
  firebase_auth: ^4.1.4
  provider: ^6.0.4
  cloud_firestore: ^4.1.0
  google_nav_bar: ^5.0.6
  carousel_slider: ^4.1.1
  dots_indicator: ^2.1.0
  url_launcher: ^6.1.7
  flutter_native_splash: ^2.2.16
  flutter_offline: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo app.jpg"

  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#101536"
  image: assets/logo app.jpg
  fullscreen: true
flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/carousel_images/
    - assets/social_icons/
    - assets/about_app/

