// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYLLoJ0G-OaemSdTGF5YcnQXUT4AeLC_0',
    appId: '1:121651393592:web:0e93e774b628508341a2cd',
    messagingSenderId: '121651393592',
    projectId: 'body-building-295c3',
    authDomain: 'body-building-295c3.firebaseapp.com',
    storageBucket: 'body-building-295c3.appspot.com',
    measurementId: 'G-V78VT1F3JY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtJ5hC6H0Ibo10QkGX9kbNTX33aOjDfAA',
    appId: '1:121651393592:android:9af8f008b8dbc89a41a2cd',
    messagingSenderId: '121651393592',
    projectId: 'body-building-295c3',
    storageBucket: 'body-building-295c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqYCnheckThEyLUY8CDyGKX_HWOR4vYjU',
    appId: '1:121651393592:ios:427badd3d695311e41a2cd',
    messagingSenderId: '121651393592',
    projectId: 'body-building-295c3',
    storageBucket: 'body-building-295c3.appspot.com',
    iosClientId: '121651393592-vveat98klkq0omoihr9ukiki17bk57rh.apps.googleusercontent.com',
    iosBundleId: 'com.example.bodyBuilding',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqYCnheckThEyLUY8CDyGKX_HWOR4vYjU',
    appId: '1:121651393592:ios:427badd3d695311e41a2cd',
    messagingSenderId: '121651393592',
    projectId: 'body-building-295c3',
    storageBucket: 'body-building-295c3.appspot.com',
    iosClientId: '121651393592-vveat98klkq0omoihr9ukiki17bk57rh.apps.googleusercontent.com',
    iosBundleId: 'com.example.bodyBuilding',
  );
}
